#region COPYRIGHT
// (c)2012 MuchDifferent. All Rights Reserved.
#endregion
#define UNITY_BUILD //by WuNan @2016/09/18 添加uLink源码工程中的条件编译符号
// WARNING: The following code is auto generated by a text template and may be overwritten at any time.

namespace uLink
{
	internal static partial class SafePlayerPrefs
	{
		public static void TrySetInt(string key, int value)
		{
#if UNITY_BUILD
			try
			{
				UnityEngine.PlayerPrefs.SetInt(key, value);
			}
			catch
			{
			}
#else
			// TODO:
#endif
		}

		public static int TryGetInt(string key)
		{
			return TryGetInt(key, default(int));
		}

		public static int TryGetInt(string key, int defaultValue)
		{
#if UNITY_BUILD
			try
			{
				return UnityEngine.PlayerPrefs.GetInt(key, defaultValue);
			}
			catch
			{
			}
#else
			// TODO:
#endif

			return defaultValue;
		}
		public static void TrySetFloat(string key, float value)
		{
#if UNITY_BUILD
			try
			{
				UnityEngine.PlayerPrefs.SetFloat(key, value);
			}
			catch
			{
			}
#else
			// TODO:
#endif
		}

		public static float TryGetFloat(string key)
		{
			return TryGetFloat(key, default(float));
		}

		public static float TryGetFloat(string key, float defaultValue)
		{
#if UNITY_BUILD
			try
			{
				return UnityEngine.PlayerPrefs.GetFloat(key, defaultValue);
			}
			catch
			{
			}
#else
			// TODO:
#endif

			return defaultValue;
		}
		public static void TrySetString(string key, string value)
		{
#if UNITY_BUILD
			try
			{
				UnityEngine.PlayerPrefs.SetString(key, value);
			}
			catch
			{
			}
#else
			// TODO:
#endif
		}

		public static string TryGetString(string key)
		{
			return TryGetString(key, default(string));
		}

		public static string TryGetString(string key, string defaultValue)
		{
#if UNITY_BUILD
			try
			{
				return UnityEngine.PlayerPrefs.GetString(key, defaultValue);
			}
			catch
			{
			}
#else
			// TODO:
#endif

			return defaultValue;
		}
	}
}
